name:                handson-day20181103
version:             0.1.0.0
github:              "githubuser/handson-day20181103"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/handson-day20181103#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  handson-day20181103-0:
    main:                handson-day20181103-0.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - handson-day20181103
    - xturtle-slide
  handson-day20181103-1:
    main:                handson-day20181103-1.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - handson-day20181103
    - xturtle-slide
  handson-day20181103-2:
    main:                handson-day20181103-2.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - handson-day20181103
    - xturtle-slide
  handson-day20181103-3:
    main:                handson-day20181103-3.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - handson-day20181103
    - xturtle-slide
  handson-day20181103-4:
    main:                handson-day20181103-4.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - handson-day20181103
    - xturtle-slide

tests:
  handson-day20181103-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - handson-day20181103
